### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by helina2023** [archettialberto/federated_survival_forests#1]
Hi , How can I use it without Docker file?

**Comment by archettialberto** [comment]
Hi! To run the code without Docker you can

- Install Python 3.10
- Clone the repo with `git clone https://github.com/archettialberto/federated_survival_forests`
- Move to the repo directory with `cd federated_survival_forests`
- Create a new virtual environment with `python -m venv venv`
- Activate the environment with `source venv/bin/activate`
- Install the dependencies with `pip install -r requirements.txt`
- Clone the helper repo with `git clone https://github.com/archettialberto/scikit-survival`
- Move to the helper repo directory with `cd scikit-survival`
- Update git submodules with `git submodule update --init`
- Move back to the `federated_survival_forests` directory with `cd ..`
- Install `scikit-survival` with `pip install ./scikit-survival`

At this point, you should be able to run `python exps.py` outside Docker.

**Comment by cxie19** [comment]
Hi! I was following the steps, but I encountered a problem while installing dependencies in the requirements. txt. The error I received is as followed: 

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Please provide some advice. Thank you!

**Comment by archettialberto** [comment]
Hi! Can you provide more details about the error message? I'll see if I can help 😉
This is probably an issue of compatibility on the system where the libraries are installing. Docker should prevent this from happening.

**Comment by cxie19** [comment]
Hi Alberto! Thank you for your reply. Actually, I had the issues of installing as well while using Docker. I am quite new to Docker. The following is the error I got when I was trying to install the Docker image:

<img width="1125" alt="error_1" src="https://github.com/archettialberto/federated_survival_forests/assets/90215497/563c6bdd-7f52-4982-ac69-7d3deccec03f">
<img width="1125" alt="error_2" src="https://github.com/archettialberto/federated_survival_forests/assets/90215497/e8642a71-814f-4a2c-8d68-c5a0d5ffd9fb">
<img width="1128" alt="error_3" src="https://github.com/archettialberto/federated_survival_forests/assets/90215497/9462619c-d9b5-4726-9db4-52934f9317d4">

Thank you for your help in advance.

**Comment by archettialberto** [comment]
Yep, there was an inconsistency on my part in the `scikit-survival` installation. Thanks for pointing out the issue! 😃 
I got the same error on my machine, but now it should work by just running the `docker-compose` command, as it will download a prebuilt Docker image from [here](https://hub.docker.com/repository/docker/aarchetti/fedsurf/general). I updated the README accordingly. I hope this helps!

**Comment by cxie19** [comment]
Thank you for resolving the issue so quickly. In addition, I have a question about loading data sets in the python file. The experiment has the following data sets GBSG2, metabric, support2, flchain, and Aids2.

Are they loaded from the python package like sksurv automatically while running the exps.py? What if I would like to import my own data sets for federated survival forests? Could you please provide some guidance? 

Also, do you have any suggestions for setting the parameters for random survival forests and number of trees to train? 

Thank you.

**Comment by archettialberto** [comment]
Yes, the supported datasets are loaded automatically in the script. If you want to add your own dataset, the procedure is the same as the METABRIC dataset. Go to `data.py` and create a function to return the dataset loaded as a Pandas dataframe. Let's call it `get_my_df`. The code assumes that `get_my_df` returns a Pandas dataframe having
* A boolean column called `event` to indicate whether a sample is censored or not
* A column called `time` where event (or censorship) times are stored
* Each feature column representing numerical variables named as `num_<column_name>` for preprocessing
* Each feature column representing categorical variables named as `fac_<column_name>` for preprocessing
* Other columns that do not need preprocessing can be named as you wish without the `num_` or `fac_` prefixes

Then, you can add `get_my_df` to `DATASETS_BEYOND_SURVSET` as
```
DATASETS_BEYOND_SURVSET = {
    "metabric": get_metabric_df,
    "my_dataset_name": get_my_df,
}
```

Finally, add your dataset as `DATASETS = ["my_dataset_name"]` in `exps.py`.

At this point, your dataset will be loaded, preprocessed, split, and (hopefully) learned by each of the survival models implemented. 

Concerning the RSF parameters, according to the dataset I used, the most influential parameters were `max_depth` (major differences between `1` and `None`) and `n_estimators` (it is not always the case that "the higher, the better"). Also, remember to put `n_jobs` to -1 to allow for parallel execution, it's much faster. To tune these parameters, it may be convenient to write a separate script and find the best parameter combination with [sklearn's grid search](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html). Hope this helps!

**Comment by cxie19** [comment]
When I used it without docker, I encountered some problem while running the exps.py: 

[2025-03-17 14:59:33.862738] Training global model...
Traceback (most recent call last):
  File "./federated_survival_forests/exps.py", line 187, in <module>
       run_exps(log_dir="./logs")
  File "./federated_survival_forests/exps.py", line 90, in run_exps
      dfs.append(rsf_exp(
  File "./federated_survival_forests/models/rsf.py", line 128, in rsf_exp
    glob_c_idx, glob_c_idx_ipcw, glob_ibs = eval_rsf(glob_model, y_train, y_test, X_test)
  File "./federated_survival_forests/models/rsf.py", line 98, in eval_rsf
    survs = [avg_fn([ts[i] for ts in tree_survs]) for i in range(len(X_test))]
  File "./federated_survival_forests/models/rsf.py", line 98, in <listcomp>
    survs = [avg_fn([ts[i] for ts in tree_survs]) for i in range(len(X_test))]
  File "./.conda/envs/federated_survival_forests/lib/python3.10/site-packages/sksurv/functions.py", line 153, in avg_fn
    return sum(fns[1:], start=fns[0]) / len(fns)
  File "./.conda/envs/federated_survival_forests/lib/python3.10/site-packages/sksurv/functions.py", line 126, in __add__
    y = self(x) + other(x)
  File "./.conda/envs/federated_survival_forests/lib/python3.10/site-packages/sksurv/functions.py", line 99, in __call__
    raise ValueError(f"x must be within [{self.domain[0]:f}; {self.domain[1]:f}]")
ValueError: x must be within [0.000000; inf]

Could you help me with it? Thank you.

**Comment by archettialberto** [comment]
Hello, I have two suggestions:
- The issue can be related to the implementation of [scikit-survival](https://scikit-survival.readthedocs.io/en/stable/), which requires test times to be within the interval of training times. The quickest solution is to filter test samples so that you retain only the ones strictly within the minimum and maximum times in the training set.
- If this does not work, the code is generating some negative survival functions for some reason, which is not valid. You can add a [clip](https://numpy.org/doc/2.1/reference/generated/numpy.clip.html) operation to ensure that the values stay in the correct (positive) interval.
